CT_DEFAULT_LIMIT = 1000

CT_CONFIG_FILE_RELATIVE_PATH = "./server_cfg.ini"
CT_SQLITE_FILE_RELATIVE_PATH = "./db/rome.db"

#
# LOGIN MESSAGES
#
CT_LOGIN_TOOMUCH_SCOPES_MSG = "Select only one role for user"
CT_LOGIN_UNKNWON_USER_MSG = "Unknown login/password"
CT_LOGIN_BAD_SCOPE_MSG = "No matching scope for user"

#
# NAMES AND CAPTIONS OF CUSTOM CASES USED IN CUSTOM EXCEPTIONS
#
CT_CC_BAD_LOGIN = 'CT_CC_BAD_LOGIN'
CT_CC_UNKNWON_APPDB_USER = 'CT_CC_UNKNWON_APPDB_USER'
CT_CC_USER_HAS_NO_SCOPE = 'CT_CC_USER_HAS_NO_SCOPE'
CT_CC_DB_LINK_IS_OFF = 'CT_CC_DB_LINK_IS_OFF'
CT_CC_UNAUTHORIZED_USER_SCOPE = 'CT_CC_UNAUTHORIZED_USER_SCOPE'
CT_CC_MULTIPLE_SCOPES_NOT_ALLOWED = 'CT_CC_MULTIPLE_SCOPES_NOT_ALLOWED'
CT_CC_UNAUTHORIZED_OPERATION_FOR_SCOPE = 'CT_CC_UNAUTHORIZED_OPERATION_FOR_SCOPE'
CT_CC_INTEGRITY_ADD_RECORD_FAILURE = 'CT_CC_INTEGRITY_ADD_RECORD_FAILURE'
CT_CC_INTEGRITY_UPDATE_RECORD_FAILURE = 'CT_CC_INTEGRITY_UPDATE_RECORD_FAILURE'
CT_CC_INTEGRITY_BULK_UPDATE_FAILURE = 'CT_CC_INTEGRITY_BULK_UPDATE_FAILURE'
CT_CC_INTEGRITY_DUPLICATE_VALUE_FAILURE = 'CT_CC_INTEGRITY_DUPLICATE_VALUE_FAILURE'
CT_CC_FORBIDDEN_RECORD_DELETION = 'CT_CC_FORBIDDEN_RECORD_DELETION'
CT_CC_FORBIDDEN_RECORD_DELETION_DEPENDENCIES = 'CT_CC_FORBIDDEN_RECORD_DELETION_DEPENDENCIES'
CT_CC_MODEL_CHANGED = 'CT_CC_MODEL_CHANGED'
CT_CC_EXPIRED_TOKEN = 'CT_CC_EXPIRED_TOKEN'
CT_CC_INVALID_TOKEN_VERSION = 'CT_CC_INVALID_TOKEN_VERSION'
CT_CC_UNAUTHORIZED_OBJECT_FOR_USER = 'CT_CC_UNAUTHORIZED_OBJECT_FOR_USER'

#
# ENVIRONEMENT VARIABLES
#
CT_ENV_API_TITLE= 'MY_API_TITLE'
CT_ENV_APP_TITLE= 'MY_APP_TITLE'
CT_ENV_AUTHENTICATION_MODE = 'MY_API_AUTHENTICATION_MODE'
CT_ENV_AUTHENTICATION_MODE_SIMPLE = 'simple'
CT_ENV_AUTHENTICATION_MODE_FULL = 'full'
CT_ENV_HOSTNAME = 'MY_API_HOSTNAME'
CT_ENV_DEV_PORT = 'MY_API_LOCAL_DEV_PORT'
CT_ENV_SECRET_KEY = 'MY_API_SECRET_KEY'
CT_ENV_EXECUTION_MODE = 'MY_API_EXECUTION_MODE'
CT_EXECUTION_MODE_DEVELOPMENT = 'development'
CT_EXECUTION_MODE_TEST = 'test'
CT_EXECUTION_MODE_PRODUCTION = 'production'

CT_ENV_LOGGING_LEVEL = 'MY_API_LOGGING_LEVEL'
CT_ENV_UNITEID_GENERIC_PASSWD = 'MY_API_UNITEID_GENERIC_PASSWD'
CT_ENV_DB_ENGINE_ECHO = 'MY_API_DB_ENGINE_ECHO'
CT_ENV_DB_ENGINE_CREATE_ALL = 'MY_API_DB_ENGINE_CREATE_ALL'
CT_ENV_DB_DRIVER = 'MY_API_DB_ENGINE_DRIVER'

CT_ENV_EXECUTION_MODES_LIST = {CT_EXECUTION_MODE_PRODUCTION,
                               CT_EXECUTION_MODE_DEVELOPMENT,
                               CT_EXECUTION_MODE_TEST}
CT_ENV_AUTHENTICATION_MODES_LIST = {CT_ENV_AUTHENTICATION_MODE_SIMPLE,
                                    CT_ENV_AUTHENTICATION_MODE_FULL}
CT_DB_USERNAME_KEYS_DICT = {CT_EXECUTION_MODE_PRODUCTION: 'MY_API_DB_PROD_USERNAME',
                            CT_EXECUTION_MODE_TEST: 'MY_API_DB_TEST_USERNAME',
                            CT_EXECUTION_MODE_DEVELOPMENT: 'MY_API_DB_DEV_USERNAME'}
CT_DB_USERPWD_KEYS_DICT = {CT_EXECUTION_MODE_PRODUCTION: 'MY_API_DB_PROD_USERPASSWD',
                           CT_EXECUTION_MODE_TEST: 'MY_API_DB_TEST_USERPASSWD',
                           CT_EXECUTION_MODE_DEVELOPMENT: 'MY_API_DB_DEV_USERPASSWD'}
CT_DB_HOSTNAME_KEYS_DICT = {CT_EXECUTION_MODE_PRODUCTION: 'MY_API_DB_PROD_HOSTNAME',
                            CT_EXECUTION_MODE_TEST: 'MY_API_DB_TEST_HOSTNAME',
                            CT_EXECUTION_MODE_DEVELOPMENT: 'MY_API_DB_DEV_HOSTNAME'}

#
# LOGGING LEVELS
#
CT_LOGGING_LEVEL_DEBUG = 10
CT_LOGGING_LEVEL_INFO = 20
CT_LOGGING_LEVEL_WARNING = 30
CT_LOGGING_LEVEL_ERROR = 40
CT_LOGGING_LEVEL_CRITICAL = 50

CT_API_LOGGING_LEVELS = {'debug': CT_LOGGING_LEVEL_DEBUG,
                         'info': CT_LOGGING_LEVEL_INFO,
                         'warning': CT_LOGGING_LEVEL_WARNING,
                         'error': CT_LOGGING_LEVEL_ERROR,
                         'critical': CT_LOGGING_LEVEL_CRITICAL}


#
# NAMES AND CAPTIONS OF CUSTOM CASES USED IN CUSTOM EXCEPTIONS
#
CT_CC_BAD_LOGIN = 'CT_CC_BAD_LOGIN'
CT_CC_UNKNWON_APPDB_USER = 'CT_CC_UNKNWON_APPDB_USER'
CT_CC_USER_HAS_NO_SCOPE = 'CT_CC_USER_HAS_NO_SCOPE'
CT_CC_DB_LINK_IS_OFF = 'CT_CC_DB_LINK_IS_OFF'
CT_CC_UNAUTHORIZED_USER_SCOPE = 'CT_CC_UNAUTHORIZED_USER_SCOPE'
CT_CC_MULTIPLE_SCOPES_NOT_ALLOWED = 'CT_CC_MULTIPLE_SCOPES_NOT_ALLOWED'
CT_CC_UNAUTHORIZED_OPERATION_FOR_SCOPE = 'CT_CC_UNAUTHORIZED_OPERATION_FOR_SCOPE'
CT_CC_INTEGRITY_ADD_RECORD_FAILURE = 'CT_CC_INTEGRITY_ADD_RECORD_FAILURE'
CT_CC_INTEGRITY_UPDATE_RECORD_FAILURE = 'CT_CC_INTEGRITY_UPDATE_RECORD_FAILURE'
CT_CC_INTEGRITY_BULK_UPDATE_FAILURE = 'CT_CC_INTEGRITY_BULK_UPDATE_FAILURE'
CT_CC_INTEGRITY_DUPLICATE_VALUE_FAILURE = 'CT_CC_INTEGRITY_DUPLICATE_VALUE_FAILURE'
CT_CC_FORBIDDEN_RECORD_DELETION = 'CT_CC_FORBIDDEN_RECORD_DELETION'
CT_CC_FORBIDDEN_RECORD_DELETION_DEPENDENCIES = 'CT_CC_FORBIDDEN_RECORD_DELETION_DEPENDENCIES'
CT_CC_MODEL_CHANGED = 'CT_CC_MODEL_CHANGED'
CT_CC_EXPIRED_TOKEN = 'CT_CC_EXPIRED_TOKEN'
CT_CC_INVALID_TOKEN_VERSION = 'CT_CC_INVALID_TOKEN_VERSION'
CT_CC_UNAUTHORIZED_OBJECT_FOR_USER = 'CT_CC_UNAUTHORIZED_OBJECT_FOR_USER'
CT_CC_EXT_REQUEST_TIMEOUT = 'CT_CC_EXT_REQUEST_TIMEOUT'


CT_SKIP_KEY = 'skip'
CT_LIMIT_KEY = 'limit'
CT_ONLY_FIRST_KEY = 'only_first'
CT_ORDER_BY_KEY = 'order_by'
CT_DEFAULT_ORDER_BY = 'default_order_by'
CT_PRIMARY_KEY_COLUMN = 'primary_key_column'
CT_ORDER_BY_DESC = 'order_by_desc'
CT_DB_SESSION_KEY = 'db_session'
CT_START_WITH_COLUMN_KEY = 'start_with_column'
CT_START_WITH_VALUE_KEY = 'start_with_value'
CT_PYDANTIC_ELEMENT_KEY = 'pydantic_element'
CT_ONLY_QUERY_KEY= 'only_query'
CT_CURRENT_USER_KEY= 'current_user'
